spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.8.167:3306/test
    url: jdbc:mysql://mysql:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: redis
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: -1s
        max-idle: 200
  rabbitmq:
      host: 192.168.8.167
      port: 5672
      username: root
      password: 123456
server:
  port: 8000
#mybatis:
#    # mybatis配置文件所在路径
#    config-location: classpath:mybatis/generatorConfig.xml
#    mapper-locations: classpath:resources/mapping/*.xml

#    type-aliases-package: com.example.demo2.dao